export enum THEME {
  BLUE = "BLUE",
  GRAY = "GRAY",
  DARK_GRAY = "DARK_GRAY",
  LIGHT_BLUE = "LIGHT_BLUE",
  GREEN = "GREEN",
  RED = "RED",
  BORDER_BLUE = "BORDER_BLUE",
}

export enum TABLE_ROW {
  EMAIL = "EMAIL",
  FIRST_NAME = "FIRST_NAME",
  LAST_NAME = "LAST_NAME",
  DATE_OF_BIRTH = "DATE_OF_BIRTH",
  ROLE = "ROLE",
}

export enum ROLE {
  "ADMIN" = "ADMIN",
  "EMPLOYEE" = "EMPLOYEE",
  "SUPER_ADMIN" = "SUPER_ADMIN",
}

export enum HOLIDAY_STATUS {
  DRAFT = "DRAFT",
  PUBLISH = "PUBLISH",
  VALIDATED = "VALIDATED",
  REFUSED = "REFUSED",
  IN_PROGRESS = "IN_PROGRESS",
  PASSED = "PASSED",
}

export enum DATE_FORMAT {
  YEAR_MONTH_DAY = "YYYY-MM-DD",
  DATE_TIME = "YYYY-MM-DD h:mm A",
  DAY_MONTH_YEAR = "DD/MM/YYYY",
  YEAR = "YYYY",
}

export enum DATE_PICKER_FORMAT {
  DEFAULT = "MM/dd/yyyy",
  YEAR_MONTH_HOUR_MINUTE = "MM/dd/yyyy HH:mm",
}
