openapi: 3.0.3
info:
  title: leaveManager Rest API
  description: All Item Rest API End Points
  version: 2024-W2
servers:
  - url: http://localhost:8080/api/leavemanager/v1
tags:
  - name: Employee
    description: Everything about the Employees
  - name: Holiday
    description: Everything about the Holidays
paths:
  /admin/registration:
    post:
      tags:
        - Admin
      summary: Create the super admin in the app
      description: Create the super admin of app. He is an employee by default
      operationId: createSuperAdmin
      requestBody:
        description: registration data that need to be use for create employee
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationDTO'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /admin/add:
    post:
      tags:
        - Admin
      summary: Create an admin in the app
      description: create an admin as super admin
      operationId: createAdmin
      security:
        - oAuth:
            - SUPER_ADMIN
      requestBody:
        description: registration data that need to be use for create employee
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationDTO'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /admin/employee/add:
    post:
      tags:
        - Admin
      summary: Create an employee in the app
      description: create an employee as super admin or admin
      operationId: createEmployee
      security:
        - oAuth:
            - SUPER_ADMIN,ADMIN
      requestBody:
        description: registration data that need to be use for create employee
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationDTO'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /admin/employee/all:
    get:
      tags:
        - Admin
      summary: get all employees
      description: get all employees present in the app
      operationId: getAllEmployees
      security:
        - oAuth:
            - EMPLOYEE,SUPER_ADMIN,ADMIN
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmployeeDTO'
  /employee/{employeeId}:
    get:
      tags:
        - Employee
      summary: Get Employee by id
      description: Get Employee by id. only the super admin or admin and the user account
      operationId: getEmployeeById
      security:
        - oAuth:
            - EMPLOYEE,SUPER_ADMIN,ADMIN
      parameters:
        - name: employeeId
          in: path
          description: employee ID to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeDTO'
    put:
      tags:
        - Employee
      summary: update a Employee
      description: update a Employee
      operationId: updateEmployee
      security:
        - oAuth:
            - EMPLOYEE
      parameters:
        - name: employeeId
          in: path
          description: employee ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Employee object that need to be update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationDTO'
      responses:
        201:
          description: successful operation
    delete:
      tags:
        - Employee
      summary: Delete employee by id
      description: Delete employee by id
      operationId: deleteEmployeeById
      security:
        - oAuth:
            - SUPER_ADMIN,ADMIN
      parameters:
        - name: employeeId
          in: path
          description: The id of the employee to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: successful operation

components:
  securitySchemes:
    oAuth:
      type: oauth2
      description: This API uses OAuth 2 with the Authorization Code grant flow.
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:8080/api/leavemanager/v1/api/auth/authenticate
          tokenUrl: http://localhost:8080/api/leavemanager/v1/api/auth/authenticate
          scopes:
            SUPER_ADMIN: all about super admin
            ADMIN: all about admin
            EMPLOYEE: all about employee

  schemas:
    RegistrationDTO:
      type: object
      properties:
        firstname:
          type: string
          description: employee firstname
        lastname:
          type: string
          description: employee lastname
        dateOfBirth:
          type: string
          format: date
    EmployeeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: identifier of employee
        password:
          type: string
          description: employee password
        firstname:
          type: string
          description: employee firstname
        lastname:
          type: string
          description: employee lastname
        email:
          type: string
          description: employee email
        dateOfBirth:
          type: string
          format: date
          description: employee date of birth
        isActivated:
          type: boolean
          description: the value is 'true' if the employee insert an existing email